[system]
enableSwagger=true # allow enable Swagger UI
enableClientSql=true  # allow client to submit SQL statement. It only works in debug mode. 
hotReloadSqlFile=true # hot reload server side SQL file 
writebackRequest=true # writeback the whole request rather than only traceId
writebackInBase64=false # writeback SQL in plain or base64 format
enableIpWhiteList=true # enable IP white list
enableIpBlackList=true # enable IP black list
ipWhiteList=["127.0.0.1","192.168.0.1"]
ipBlackList=["127.0.0.2","192.168.0.156"]
useResponseCompression=false # enable response compression



[[databases]]
name="sakila"  # db connection name 
dbType="mysql" # sqlite,mysql,mssql,postgresql,oracle
connectionString="Server=localhost;Port=3306;Database=sakila;Uid=root;Pwd=TOOR;"    
sqlFileHome="./sql"   #sql file home

[[databases]]
name="northwind" # db connection name 
dbType="mssql" # sqlite,mysql,mssql,postgresql,oracle
connectionString="Server=localhost;Database=Oee;User Id=sa;Password=root;Encrypt=True;TrustServerCertificate=True"    
sqlFileHome="./sql"  #sql file home
