[system]
enableSwagger=true 
enableClientSql=true  #allow client to submit SQL statement. It only works in debug mode. 
useResponseCompression=true
hotReloadSqlFile=true
writebackRequest=true # 在response中是否要回写完整的request
firewallStrategies=["clientIpWhiteList","clientIpBlackList"]
clientIpWhiteList=["127.0.0.1","192.168.0.1"]
clientIpBlackList=["127.0.0.1","192.168.0.156"]




[[databases]]
name="db1"
dbType="mysql" # sqlite,mysql,mssql,postgresql,oracle
connectionString="Server=localhost;Port=3306;Database=sakila;Uid=root;Pwd=TOOR;"    
sqlFileHome="D://my_workspace//source//src1//github//MyREST//MyREST//src//MyREST//bin//Debug//net7.0"   #sql file home

[[databases]]
name="db2"
dbType="mysql" # sqlite,mysql,mssql,postgresql,oracle
connectionString="Server=localhost;Port=3306;Database=sakila;Uid=root;Pwd=TOOR;"    
sqlFileHome="d:/"   #sql file home


[authaaaa]
enabled = true  #是否启用 authentication
route = "/auth"
userTable="myrest_users"
type = "body"
encrypt = "MD5"
accessTokenExpires=10	#unit:minute
refreshTokenExpire=60  #unit:minute
jwtKey="secret"
jwtAlgo="HS256"