[system]
enableSwagger=true # allow enable Swagger UI
enableClientSql=true  # allow client to submit SQL statement. It only works in debug mode. 
hotReloadSqlFile=true # hot reload server side SQL file 
writebackRequest=true # writeback the whole request rather than only traceId
writebackInBase64=false # writeback SQL in plain or base64 format
useResponseCompression=false # enable response compression

[firewall]
enableIpWhiteList=true # enable IP white list
enableIpBlackList=true # enable IP black list
ipWhiteList=["127.0.0.1","192.168.0.1"]
ipBlackList=["127.0.0.2","192.168.0.156"]


[basicAuth]
enableBasicAuth=true # enable Basic Auth
username="user123"
password="password123"


[jwtAuth]
enableJwtAuth=false # enable JWT Auth
audience="myrest client"
validateAudience=true
issuer="some auth server"
validateIssuer=true
publicKey="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuDnJaGFITMmnFrYrW1ZMK9YXE+9mSoJRPDLGu33VepOaA3+NUWAaASW8xzL+pWWIFLgvLwcMYMIv8YvSRNazlMrpsdtLs7SYEBx5Y1m3RC0p468vtUVyWmnFRoGpG0VRl9n5eNSz4iJm2zb+z6QI5DRd+KVVHLpwwyKWXTHwmgy2mvvT0ohBjKnW8/LX/r0H00qJd5fJVRwKWpGUX4/UhUPwO/lNwKbukV+JHKOQ6ytbgHLCgTISxYtT3dszBVMYeoQ9YlEqVcaUeZKQIynGgwBLEgVUhntvJgSU2DwbC6yPUBl0xXamtZiz93DE5bWrTCgaSqPGRRDOtyEMemHtkQIDAQAB"

 

[[databases]]
name="sakila"  # db connection name 
dbType="mysql" # sqlite,mysql,mssql,postgresql,oracle
connectionString="Server=localhost;Port=3306;Database=sakila;Uid=root;Pwd=TOOR;"    
sqlFileHome="./sql"   #sql file home

[[databases]]
name="northwind" # db connection name 
dbType="mssql" # sqlite,mysql,mssql,postgresql,oracle
connectionString="Server=localhost;Database=Oee;User Id=sa;Password=root;Encrypt=True;TrustServerCertificate=True"    
sqlFileHome="./sql"  #sql file home
