[system]
debug = true  #启用debug模式, 将不需要进行 authentication 
port = 3000
host = "localhost"
basePath ="/myrest"
enableClientSql =true  #allow client to submit SQL statement. It only works in debug mode. 
clientAccessPolicy=["whiteList","blackList"]
clientIpWhiteList=["localhost","192.168.0.1"]
clientIpBlackList=["192.168.0.155"]

[auth]
enabled = true  #是否启用 authentication
route = "/auth"
userTable="myrest_users"
type = "body"
encrypt = "MD5"
accessTokenExpires=10	#unit:minute
refreshTokenExpire=60  #unit:minute
jwtKey="secret"
jwtAlgo="HS256"


[databases]
   [database.db1]
    isMainDb=true  #MainDb or StdDb, auth userTable will only stored in mainDb
    dbType="mysql" # sqlite,mysql,mssql,postgresql,oracle
	connectionString=""
    route="/db1"
	sqlFileHome=""   #sql file home

   [database.db2]
    isMainDb=false  #MainDb or StdDb, auth userTable will only stored in mainDb
    dbType="mysql" # sqlite,mysql,mssql,postgresql,oracle
	connectionString=""
    route="/db2"
	sqlFileHome=""   #sql file home

